apiVersion: apps/v1
kind: Deployment

metadata:
  name: inventory-service
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: inventory-service

  template:
    metadata:
      labels:
        app: inventory-service

    spec:
      containers:
        - name: inventory-service
          image: rajni2209/inventory-service:v1

          ports:
            - containerPort: 9095

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_PORT
              value: "3306"

          envFrom:
            - configMapRef:
                name: ecommerce-config

            - secretRef:
                name: ecommerce-secret