apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rajni2209/api-gateway:v1
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_URL
              value: http://server-registry:8761/eureka

            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

