security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-my-super-secret-key}

spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  application:
    name: api-gatway