apiVersion: v1
kind: ConfigMap

metadata:
  name: mariadb-init-script
  namespace: ecommerce

data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS search_db;

    CREATE DATABASE IF NOT EXISTS ai_service;