apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  EUREKA_URL: "http://server-registry:8761/eureka"
  CONFIG_SERVER_URL: "http://config-server:8888"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  ELASTICSEARCH_URL: "http://elasticsearch:9200"

  SEARCH_SERVICE_URL: "http://search-service:9099"

  OLLAMA_BASE_URL: "http://ollama:11434"
  