apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: rajni
  JWT_SECRET: my-super-secret-key-my-super-secret-key
  