apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-registry
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-registry
  template:
    metadata:
      labels:
        app: server-registry
    spec:
      containers:
        - name: server-registry
          image:  rajni2209/server-registry:v1
          ports:
            - containerPort: 8761
      