name: Deploy to Amazon EKS

on:
  workflow_run:
    workflows:
      - Build & Push Docker Images using GitHub Actions
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: e-commerce-prod
      RELEASE_NAME: ecommerce
      HELM_PATH: ./k8s-helm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Verify Cluster Connection
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get ns

      - name: Update Helm Dependencies
        run: |
          helm dependency update $HELM_PATH

      - name: Helm Lint
        run: |
          helm lint $HELM_PATH

      - name: Deploy Application
        shell: bash
        run: |

          SHA=${{ github.event.workflow_run.head_sha }}

          SERVICES=(
            api-gatway
            auth-service
            cart-service
            config-server
            inventory-service
            order-service
            payment-service
            product-service
            profile-service
            search-service
            server-registry
          )

          HELM_ARGS=""

          for SERVICE in "${SERVICES[@]}"
          do
            HELM_ARGS="$HELM_ARGS --set ${SERVICE}.image.tag=${SERVICE}-${SHA}"
          done

          echo "Deploying commit: $SHA"

          helm upgrade \
            --install $RELEASE_NAME \
            $HELM_PATH \
            $HELM_ARGS \
            --wait \
            --timeout 10m

      - name: Wait for Rollout
        shell: bash
        run: |

          SERVICES=(
            config-server
            server-registry
            auth-service
            cart-service
            inventory-service
            order-service
            payment-service
            product-service
            profile-service
            search-service
            api-gateway
          )

          for SERVICE in "${SERVICES[@]}"
          do
            echo "======================================"
            echo "Waiting for ecommerce-$SERVICE"

            kubectl rollout status deployment/ecommerce-$SERVICE \
              --timeout=300s
          done

      - name: Verify Deployment
        run: |
          echo "========== Nodes =========="
          kubectl get nodes

          echo "========== Deployments =========="
          kubectl get deployments

          echo "========== Pods =========="
          kubectl get pods -o wide

          echo "========== Services =========="
          kubectl get svc

          echo "========== Ingress =========="
          kubectl get ingress

          echo "========== Helm Release =========="
          helm list
